# Copyright Â© 2025 Colden Cullen
# SPDX-License-Identifier: MIT

default_stages:
  - pre-commit
  - pre-push

default_install_hook_types:
  - commit-msg
  - pre-commit
  - pre-push

ci:
  autofix_commit_msg: "fix(pre-commit): auto fixes from pre-commit hooks"
  autoupdate_commit_msg: "chore(deps): pre-commit autoupdate"
  skip:
    - no-commit-to-branch
    - hawkeye-format
    - golangci-lint-config-verify
    - golangci-lint-full
    - golangci-lint-fmt
    - buf-lint
    - buf-format
    - zizmor

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: v1.6.1
    hooks:
      - id: check-pre-commit-ci-config

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-toml
      - id: check-yaml
        args:
          - --allow-multiple-documents
          - --unsafe
      - id: check-added-large-files
      - id: mixed-line-ending
      - id: detect-private-key
      - id: no-commit-to-branch

  - repo: https://gitlab.com/bmares/check-json5
    rev: v1.0.1
    hooks:
      - id: check-json5

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.8
    hooks:
      - id: commitizen
        stages:
          - commit-msg
          - manual

  - repo: https://github.com/korandoru/hawkeye
    rev: v6.5.1
    hooks:
      - id: hawkeye-format

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.10.1
    hooks:
      - id: golangci-lint-config-verify
      - id: golangci-lint-full
      - id: golangci-lint-fmt

  - repo: https://github.com/bufbuild/buf
    rev: v1.65.0
    hooks:
      - id: buf-lint
      - id: buf-format

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.11
    hooks:
      - id: actionlint

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.22.0
    hooks:
      - id: zizmor
